"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, Download, Copy, Clock, Sparkles } from "lucide-react";
import jsPDF from "jspdf";

type Finish = "gloss" | "satin" | "matte" | "chrome" | "ppf";
type Climate = "mild" | "moderate" | "hot" | "extreme";
type Care = "minimal" | "average" | "good" | "excellent";

const baseLifespan: Record<Finish, number> = {
  gloss: 7,
  satin: 6,
  matte: 5,
  chrome: 3,
  ppf: 10,
};

const climateMod: Record<Climate, number> = {
  mild: 1.15,
  moderate: 1.0,
  hot: 0.75,
  extreme: 0.6,
};

const careMod: Record<Care, number> = {
  minimal: 0.7,
  average: 1.0,
  good: 1.15,
  excellent: 1.3,
};

export default function LifespanPredictor() {
  const [finish, setFinish] = useState<Finish>("gloss");
  const [climate, setClimate] = useState<Climate>("moderate");
  const [garaged, setGaraged] = useState(false);
  const [care, setCare] = useState<Care>("average");
  const [installYear, setInstallYear] = useState(new Date().getFullYear());

  const years = baseLifespan[finish] * climateMod[climate] * careMod[care] * (garaged ? 1.25 : 1);
  const low = Math.round(years * 0.85 * 10) / 10;
  const high = Math.round(years * 1.15 * 10) / 10;
  const expected = Math.round(years * 10) / 10;
  const replaceYear = installYear + Math.round(expected);

  const downloadPDF = () => {
    const doc = new jsPDF();
    doc.setFillColor(244, 63, 94);
    doc.rect(0, 0, 210, 30, "F");
    doc.setTextColor(255);
    doc.setFontSize(18);
    doc.text("Wrap Lifespan Prediction", 14, 19);

    doc.setTextColor(20);
    doc.setFontSize(11);
    let y = 45;
    doc.text(`Finish: ${finish}`, 14, y); y += 7;
    doc.text(`Climate: ${climate}`, 14, y); y += 7;
    doc.text(`Garaged: ${garaged ? "Yes" : "No"}`, 14, y); y += 7;
    doc.text(`Care level: ${care}`, 14, y); y += 7;
    doc.text(`Install year: ${installYear}`, 14, y); y += 14;

    doc.setFontSize(13);
    doc.text(`Expected lifespan: ${expected} years (${low}–${high})`, 14, y); y += 8;
    doc.text(`Estimated replacement year: ${replaceYear}`, 14, y);

    doc.setFontSize(8);
    doc.setTextColor(120);
    doc.text("Generated by wrapflow.site — estimates only, actual lifespan varies.", 14, 285);
    doc.save("wrap-lifespan.pdf");
  };

  const copyText = () => {
    const t = `WRAP LIFESPAN PREDICTION
Finish: ${finish}
Climate: ${climate}
Garaged: ${garaged ? "Yes" : "No"}
Care: ${care}
Install year: ${installYear}

Expected lifespan: ${expected} years (range ${low}–${high})
Estimated replacement: ${replaceYear}

via wrapflow.site`;
    navigator.clipboard.writeText(t);
  };

  return (
    <main className="relative min-h-screen bg-[#06060a] text-zinc-100">
      <div aria-hidden="true" className="pointer-events-none absolute inset-0 -z-10 overflow-hidden">
        <div className="absolute top-0 left-[10%] h-[500px] w-[500px] rounded-full bg-rose-400/20 blur-[120px]" />
        <div className="absolute top-[600px] right-[5%] h-[400px] w-[400px] rounded-full bg-amber-400/10 blur-[120px]" />
      </div>

      <header className="sticky top-4 z-50 mx-4 lg:mx-8">
        <nav className="mx-auto flex max-w-5xl items-center justify-between rounded-full border border-white/10 bg-white/[0.04] px-6 py-3 shadow-[inset_0_1px_0_0_rgba(255,255,255,0.08)] backdrop-blur-2xl">
          <Link href="/" className="group flex items-center gap-2 text-sm text-zinc-400 transition hover:text-white">
            <ArrowLeft className="h-4 w-4 transition-transform group-hover:-translate-x-0.5" />
            Back to tools
          </Link>
          <div className="flex items-center gap-2 rounded-full bg-gradient-to-br from-rose-400 to-rose-600 p-px">
            <div className="flex items-center gap-2 rounded-full bg-[#0a0a12]/85 px-3 py-1.5 text-sm font-medium">
              <Sparkles className="h-4 w-4 text-rose-300" />
              Lifespan Predictor
            </div>
          </div>
        </nav>
      </header>

      <section className="mx-auto max-w-5xl px-6 py-12 lg:px-8">
        <div className="text-center mb-10">
          <p className="bg-gradient-to-r from-rose-400 to-amber-400 bg-clip-text text-xs font-medium uppercase tracking-[0.25em] text-transparent">Predictor</p>
          <h1 className="mt-2 text-4xl font-medium tracking-tight text-white sm:text-5xl">
            How long will your <span className="bg-gradient-to-r from-rose-200 to-amber-200 bg-clip-text text-transparent">wrap last?</span>
          </h1>
          <p className="mx-auto mt-3 max-w-xl text-sm text-zinc-400">
            Set your finish, climate, and care habits — get a realistic lifespan estimate.
          </p>
        </div>

        <div className="grid gap-6 lg:grid-cols-[1fr_400px]">
          {/* INPUTS */}
          <div className="space-y-6 rounded-2xl border border-white/10 bg-white/[0.03] p-6 backdrop-blur-xl">
            {/* Finish */}
            <div>
              <p className="mb-3 text-xs font-medium uppercase tracking-wider text-zinc-400">Finish type</p>
              <div className="grid grid-cols-3 gap-2 sm:grid-cols-5">
                {(["gloss", "satin", "matte", "chrome", "ppf"] as Finish[]).map((f) => (
                  <button key={f} onClick={() => setFinish(f)}
                    className={"rounded-lg border px-3 py-2 text-sm capitalize transition " + (finish === f ? "border-rose-400/50 bg-rose-400/10 text-white" : "border-white/10 bg-white/[0.02] text-zinc-400 hover:text-white")}>{f}</button>
                ))}
              </div>
            </div>

            {/* Climate */}
            <div>
              <p className="mb-3 text-xs font-medium uppercase tracking-wider text-zinc-400">Climate</p>
              <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
                {([["mild", "Mild"], ["moderate", "Moderate"], ["hot", "Hot/Sunny"], ["extreme", "Extreme heat"]] as const).map(([k, l]) => (
                  <button key={k} onClick={() => setClimate(k)}
                    className={"rounded-lg border px-3 py-2 text-sm transition " + (climate === k ? "border-rose-400/50 bg-rose-400/10 text-white" : "border-white/10 bg-white/[0.02] text-zinc-400 hover:text-white")}>{l}</button>
                ))}
              </div>
            </div>

            {/* Care */}
            <div>
              <p className="mb-3 text-xs font-medium uppercase tracking-wider text-zinc-400">Care level</p>
              <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
                {([["minimal", "Minimal"], ["average", "Average"], ["good", "Good"], ["excellent", "Excellent"]] as const).map(([k, l]) => (
                  <button key={k} onClick={() => setCare(k)}
                    className={"rounded-lg border px-3 py-2 text-sm transition " + (care === k ? "border-rose-400/50 bg-rose-400/10 text-white" : "border-white/10 bg-white/[0.02] text-zinc-400 hover:text-white")}>{l}</button>
                ))}
              </div>
            </div>

            {/* Garaged */}
            <div className="flex items-center justify-between rounded-xl border border-white/10 bg-white/[0.02] px-4 py-3">
              <div>
                <p className="text-sm text-white">Garaged when not in use?</p>
                <p className="text-xs text-zinc-500">Adds ~25% lifespan</p>
              </div>
              <button onClick={() => setGaraged(!garaged)}
                className={"relative h-6 w-11 rounded-full transition " + (garaged ? "bg-rose-400" : "bg-white/10")}>
                <span className={"absolute top-0.5 h-5 w-5 rounded-full bg-white transition " + (garaged ? "left-5" : "left-0.5")} />
              </button>
            </div>

            {/* Install year */}
            <div>
              <p className="mb-3 text-xs font-medium uppercase tracking-wider text-zinc-400">Install year</p>
              <input type="number" min={2010} max={2030} value={installYear}
                onChange={(e) => setInstallYear(Number(e.target.value))}
                className="w-full rounded-lg border border-white/10 bg-white/[0.02] px-4 py-2 text-sm text-white focus:border-rose-400/50 focus:outline-none" />
            </div>
          </div>

          {/* RESULT */}
          <div className="rounded-2xl border border-rose-400/30 bg-rose-400/5 p-6 backdrop-blur-xl">
            <div className="mb-2 flex items-center gap-2">
              <Clock className="h-5 w-5 text-rose-300" />
              <p className="text-xs font-medium uppercase tracking-wider text-rose-300">Predicted lifespan</p>
            </div>
            <p className="text-5xl font-medium text-white">{expected}<span className="text-2xl text-zinc-400"> yrs</span></p>
            <p className="mt-1 text-sm text-zinc-400">range: {low} – {high} years</p>

            <div className="my-6 h-px bg-white/10" />

            <p className="text-xs text-zinc-500">Estimated replacement year</p>
            <p className="mt-1 text-3xl font-medium text-white">{replaceYear}</p>

            <div className="mt-6 space-y-2">
              <button onClick={downloadPDF}
                className="flex w-full items-center justify-center gap-2 rounded-full bg-gradient-to-b from-rose-300 to-rose-500 px-4 py-2.5 text-sm font-medium text-zinc-900 transition hover:from-rose-200 hover:to-rose-400">
                <Download className="h-4 w-4" /> Download PDF
              </button>
              <button onClick={copyText}
                className="flex w-full items-center justify-center gap-2 rounded-full border border-white/10 bg-white/[0.04] px-4 py-2.5 text-sm font-medium text-zinc-200 transition hover:bg-white/[0.08]">
                <Copy className="h-4 w-4" /> Copy as text
              </button>
            </div>

            <p className="mt-4 text-[10px] text-zinc-500">Estimate only — actual lifespan varies by install quality, vinyl brand, and use.</p>
          </div>
        </div>
      </section>
    </main>
  );
}