"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, Shield, Download, Copy } from "lucide-react";
import jsPDF from "jspdf";

type Zone = "hood" | "fenders" | "bumper" | "mirrors" | "rockers" | "aPillars" | "doors" | "rearBumper" | "fullRear" | "roof";

const zones: { key: Zone; label: string; priority: number; description: string }[] = [
  { key: "bumper", label: "Front Bumper", priority: 1, description: "Highest impact zone — first to hit rock chips" },
  { key: "hood", label: "Hood (full)", priority: 1, description: "Heavy chip exposure at highway speed" },
  { key: "fenders", label: "Front Fenders", priority: 2, description: "Side spray from tires & road debris" },
  { key: "mirrors", label: "Side Mirrors", priority: 2, description: "Common scrape & impact area" },
  { key: "aPillars", label: "A-Pillars", priority: 2, description: "Insect/highway debris zone" },
  { key: "rockers", label: "Rocker Panels", priority: 3, description: "Stone chips kicked up by tires" },
  { key: "doors", label: "Door Cups & Edges", priority: 3, description: "Fingernail scratches" },
  { key: "rearBumper", label: "Rear Bumper Top", priority: 3, description: "Loading scratches" },
  { key: "roof", label: "Roof", priority: 4, description: "UV & weather only" },
  { key: "fullRear", label: "Full Rear Panels", priority: 4, description: "Comprehensive coverage" },
];

const packages = [
  { name: "Partial Front", zones: ["bumper"], match: (s: Set<Zone>) => s.has("bumper") && s.size <= 1 },
  { name: "Full Front", zones: ["bumper", "hood", "fenders", "mirrors", "aPillars"], match: (s: Set<Zone>) => ["bumper","hood","fenders","mirrors","aPillars"].every(z => s.has(z as Zone)) && s.size <= 5 },
  { name: "Track Package", zones: ["bumper", "hood", "fenders", "mirrors", "aPillars", "rockers", "doors"], match: (s: Set<Zone>) => s.size >= 6 && s.size <= 8 },
  { name: "Full Vehicle", zones: zones.map(z => z.key), match: (s: Set<Zone>) => s.size >= 9 },
];

export default function PPFVisualizer() {
  const [selected, setSelected] = useState<Set<Zone>>(new Set(["bumper", "hood"]));

  const toggle = (z: Zone) => {
    const n = new Set(selected);
    if (n.has(z)) n.delete(z); else n.add(z);
    setSelected(n);
  };

  const currentPackage = packages.find(p => p.match(selected))?.name || "Custom selection";
  const priorityScore = Array.from(selected).reduce((s, z) => s + (5 - (zones.find(x => x.key === z)?.priority ?? 5)), 0);

  const downloadPDF = () => {
    const doc = new jsPDF();
    doc.setFillColor(249, 115, 22);
    doc.rect(0, 0, 210, 30, "F");
    doc.setTextColor(255);
    doc.setFontSize(18);
    doc.text("PPF Coverage Plan", 14, 19);

    doc.setTextColor(20);
    doc.setFontSize(11);
    let y = 45;
    doc.text(`Package tier: ${currentPackage}`, 14, y); y += 7;
    doc.text(`Zones selected: ${selected.size}`, 14, y); y += 14;

    doc.setFontSize(12);
    doc.text("Selected zones:", 14, y); y += 8;
    doc.setFontSize(10);
    Array.from(selected).forEach((z) => {
      const zone = zones.find(x => x.key === z);
      if (zone) {
        doc.text(`• ${zone.label}`, 18, y);
        y += 6;
      }
    });

    doc.setFontSize(8);
    doc.setTextColor(120);
    doc.text("Generated by wrapflow.site", 14, 285);
    doc.save("ppf-coverage.pdf");
  };

  const copyText = () => {
    const t = `PPF COVERAGE PLAN
Package: ${currentPackage}
Zones: ${selected.size}

${Array.from(selected).map(z => `• ${zones.find(x => x.key === z)?.label}`).join("\n")}

via wrapflow.site`;
    navigator.clipboard.writeText(t);
  };

  return (
    <main className="relative min-h-screen bg-[#06060a] text-zinc-100">
      <div aria-hidden="true" className="pointer-events-none absolute inset-0 -z-10 overflow-hidden">
        <div className="absolute top-0 left-[10%] h-[500px] w-[500px] rounded-full bg-orange-400/20 blur-[120px]" />
        <div className="absolute top-[600px] right-[5%] h-[400px] w-[400px] rounded-full bg-amber-400/10 blur-[120px]" />
      </div>

      <header className="sticky top-4 z-50 mx-4 lg:mx-8">
        <nav className="mx-auto flex max-w-5xl items-center justify-between rounded-full border border-white/10 bg-white/[0.04] px-6 py-3 shadow-[inset_0_1px_0_0_rgba(255,255,255,0.08)] backdrop-blur-2xl">
          <Link href="/" className="group flex items-center gap-2 text-sm text-zinc-400 transition hover:text-white">
            <ArrowLeft className="h-4 w-4 transition-transform group-hover:-translate-x-0.5" />
            Back to tools
          </Link>
          <div className="flex items-center gap-2 rounded-full bg-gradient-to-br from-orange-400 to-orange-600 p-px">
            <div className="flex items-center gap-2 rounded-full bg-[#0a0a12]/85 px-3 py-1.5 text-sm font-medium">
              <Shield className="h-4 w-4 text-orange-300" />
              PPF Coverage
            </div>
          </div>
        </nav>
      </header>

      <section className="mx-auto max-w-5xl px-6 py-12 lg:px-8">
        <div className="text-center mb-10">
          <p className="bg-gradient-to-r from-orange-400 to-amber-400 bg-clip-text text-xs font-medium uppercase tracking-[0.25em] text-transparent">Visualizer</p>
          <h1 className="mt-2 text-4xl font-medium tracking-tight text-white sm:text-5xl">
            What should you <span className="bg-gradient-to-r from-orange-200 to-amber-200 bg-clip-text text-transparent">protect?</span>
          </h1>
          <p className="mx-auto mt-3 max-w-xl text-sm text-zinc-400">
            Toggle zones by impact priority. See which PPF package matches your selection.
          </p>
        </div>

        <div className="grid gap-6 lg:grid-cols-[1fr_400px]">
          {/* ZONES */}
          <div className="space-y-2 rounded-2xl border border-white/10 bg-white/[0.03] p-6 backdrop-blur-xl">
            {[1, 2, 3, 4].map((p) => (
              <div key={p}>
                <p className="mt-4 mb-2 text-[10px] font-medium uppercase tracking-wider text-zinc-500">
                  Priority {p} {p === 1 && "— Highest impact"}
                </p>
                {zones.filter(z => z.priority === p).map((z) => (
                  <button key={z.key} onClick={() => toggle(z.key)}
                    className={"flex w-full items-start gap-3 rounded-xl border px-4 py-3 text-left transition " + (selected.has(z.key) ? "border-orange-400/50 bg-orange-400/10" : "border-white/10 bg-white/[0.02] hover:bg-white/[0.04]")}>
                    <div className={"mt-1 flex h-4 w-4 flex-shrink-0 items-center justify-center rounded border " + (selected.has(z.key) ? "border-orange-400 bg-orange-400" : "border-white/30")}>
                      {selected.has(z.key) && <span className="text-[10px] text-zinc-900">✓</span>}
                    </div>
                    <div>
                      <p className="text-sm font-medium text-white">{z.label}</p>
                      <p className="text-xs text-zinc-500">{z.description}</p>
                    </div>
                  </button>
                ))}
              </div>
            ))}
          </div>

          {/* RESULT */}
          <div className="rounded-2xl border border-orange-400/30 bg-orange-400/5 p-6 backdrop-blur-xl">
            <p className="text-xs font-medium uppercase tracking-wider text-orange-300">Closest package match</p>
            <p className="mt-2 text-3xl font-medium text-white">{currentPackage}</p>

            <div className="my-6 h-px bg-white/10" />

            <div className="grid grid-cols-2 gap-4">
              <div>
                <p className="text-xs text-zinc-500">Zones</p>
                <p className="mt-1 text-2xl font-medium text-white">{selected.size}</p>
              </div>
              <div>
                <p className="text-xs text-zinc-500">Protection score</p>
                <p className="mt-1 text-2xl font-medium text-white">{priorityScore}</p>
              </div>
            </div>

            <div className="mt-6 space-y-2">
              <button onClick={downloadPDF}
                className="flex w-full items-center justify-center gap-2 rounded-full bg-gradient-to-b from-orange-300 to-orange-500 px-4 py-2.5 text-sm font-medium text-zinc-900 transition hover:from-orange-200 hover:to-orange-400">
                <Download className="h-4 w-4" /> Download PDF
              </button>
              <button onClick={copyText}
                className="flex w-full items-center justify-center gap-2 rounded-full border border-white/10 bg-white/[0.04] px-4 py-2.5 text-sm font-medium text-zinc-200 transition hover:bg-white/[0.08]">
                <Copy className="h-4 w-4" /> Copy as text
              </button>
            </div>

            <Link href="/wrap-cost-calculator" className="mt-4 block text-center text-xs text-orange-300 hover:underline">
              Want to price the wrap on top of this? →
            </Link>
          </div>
        </div>
      </section>
    </main>
  );
}